#!/usr/bin/env bash
# Shared nginx build configuration
# Sourced by bin/compile and .github/workflows/release.yml
# shellcheck disable=SC2034

# https://nginx.org/en/download.html
NGINX_VERSION="1.29.8"
# https://github.com/PCRE2Project/pcre2/releases
PCRE_VERSION="10.47"
# https://github.com/gliderlabs/sigil/releases
SIGIL_VERSION="0.11.5"
# https://github.com/madler/zlib/releases
ZLIB_VERSION="1.3.2"

NGINX_CONFIGURE_FLAGS=(
  --with-cpu-opt=generic
  --sbin-path=.
  --pid-path=./nginx.pid
  --conf-path=./nginx.conf
  "--with-ld-opt=-static"
  --with-http_stub_status_module
  --with-http_gzip_static_module
  --with-file-aio
  --with-pcre
  "--with-cc-opt=-O2 -static -static-libgcc"
  --without-http_ssi_module
  --without-http_userid_module
  --without-http_access_module
  --without-http_autoindex_module
  --without-http_geo_module
  --without-http_map_module
  --without-http_split_clients_module
  --without-http_referer_module
  --without-http_fastcgi_module
  --without-http_uwsgi_module
  --without-http_scgi_module
  --without-http_memcached_module
  --without-http_empty_gif_module
  --without-http_browser_module
  --without-http_upstream_ip_hash_module
  --without-http_upstream_least_conn_module
  --without-http_upstream_keepalive_module
  --without-mail_pop3_module
  --without-mail_imap_module
  --without-mail_smtp_module
  --with-http_realip_module
)
